<a href="https://colab.research.google.com/github/sadhana62/AI/blob/master/Eigen_jacobi_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a Python program to implement Jacobi's method for finding the Eigen Values, Eigen Vectors of A, real Symmetric matrix.

In [ ]:
import numpy as np


In [ ]:


def jacobi_method(A, tol=1e-10, max_iterations=100):
    n = A.shape[0]
    assert np.allclose(A, A.T), "Matrix must be symmetric!"

    V = np.eye(n)

    for _ in range(max_iterations):
        # Find largest off-diagonal element
        off_diag_indices = np.triu_indices(n, 1)
        off_diag_values = np.abs(A[off_diag_indices])
        k = np.argmax(off_diag_values)
        p, q = off_diag_indices[0][k], off_diag_indices[1][k]

        if abs(A[p, q]) < tol:
            break

        # Compute rotation
        theta = 0.5 * np.arctan2(2 * A[p, q], A[q, q] - A[p, p])
        c = np.cos(theta)
        s = np.sin(theta)

        J = np.eye(n)
        J[p, p] = c
        J[q, q] = c
        J[p, q] = s
        J[q, p] = -s

        # Update A and eigenvector matrix
        A = J.T @ A @ J
        V = V @ J

    eigenvalues = np.diag(A)
    eigenvectors = V
    return eigenvalues, eigenvectors


# --- User Input Section ---
n = int(input("Enter the size of the matrix (n x n): "))
print("Enter the elements of the matrix row by row:")

A = []

# A = np.array([[4, -2, 2],
#               [-2, 2, -4],
#               [2, -4, 11]], dtype=float)
for i in range(n):
    row = list(map(float, input(f"Row {i+1}: ").split()))
    A.append(row)

A = np.array(A)


eigenvalues, eigenvectors = jacobi_method(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Enter the size of the matrix (n x n): 3
Enter the elements of the matrix row by row:
Row 1: 4  -2  2
Row 2: -2  2   -4
Row 3: 2  -4  11

Eigenvalues:
[ 0.08229129  3.66882335 13.24888536]

Eigenvectors:
[[ 0.32333806 -0.90650053  0.27149456]
 [ 0.90612325  0.21390284 -0.36494688]
 [ 0.27275108  0.36400875  0.89056413]]
